# Generated by Django 5.0.4 on 2024-04-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0002_client_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=31)),
                ('is_principal', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='client',
            new_name='Nom_client',
        ),
        migrations.CreateModel(
            name='Mesure_produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rapport', models.CharField(max_length=31)),
                ('prix', models.FloatField()),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.mesure')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vente.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Produit_commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.FloatField(editable=False, null=True)),
                ('date', models.DateField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.commande')),
                ('mesure_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vente.mesure_produit')),
            ],
        ),
    ]
