# Generated by Django 5.0.4 on 2024-04-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0003_mesure_rename_client_commande_nom_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='Nom_client',
        ),
        migrations.RemoveField(
            model_name='mesure_produit',
            name='mesure',
        ),
        migrations.RemoveField(
            model_name='mesure_produit',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit_commande',
            name='mesure_produit',
        ),
        migrations.RemoveField(
            model_name='produit_commande',
            name='commande',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='montant',
            new_name='prix_total',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('received_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite_initiale', models.FloatField(editable=False, null=True)),
                ('quantite_actuelle', models.FloatField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delai_expiration', models.PositiveIntegerField()),
                ('prix', models.FloatField()),
                ('Produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vente.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Mesure',
        ),
        migrations.DeleteModel(
            name='Mesure_produit',
        ),
        migrations.DeleteModel(
            name='Produit_commande',
        ),
    ]
